export const exampleQuestion = '员工迟到、早退在 30 分钟以内，公司会如何处罚？'

export const flowSpec = {
  width: 3720,
  height: 860,
  nodes: [
    {
      id: 'question',
      kind: 'variable',
      name: 'question',
      value: exampleQuestion,
      file: 'src/views/Chat.vue',
      why: '这是用户在输入框里打出来的原始问题，学习中心先从这个气泡开始。',
      x: 40,
      y: 90,
    },
    {
      id: 'attachments',
      kind: 'variable',
      name: 'attachments',
      value: '[]',
      file: 'src/views/Chat.vue',
      why: '聊天页允许同时带图片附件，这个数组会一起传给后端。',
      x: 40,
      y: 250,
    },
    {
      id: 'selectedKnowledgeBaseId',
      kind: 'variable',
      name: 'selectedKnowledgeBaseId',
      value: '7',
      file: 'src/views/Chat.vue / src/stores/chat.js',
      why: '它决定这次问答只能查哪个知识库，避免不同知识库互相串内容。',
      x: 40,
      y: 410,
    },
    {
      id: 'sendMessage',
      kind: 'method',
      name: 'chatStore.sendMessage()',
      value: 'sendMessage(question, attachments)',
      file: 'src/stores/chat.js',
      why: 'Pinia 里的真实方法，把页面输入变成一次流式聊天请求。',
      x: 310,
      y: 210,
    },
    {
      id: 'streamChat',
      kind: 'method',
      name: 'streamChat()',
      value: 'fetch(`${API_BASE_URL}/chat/stream`, ...)',
      file: 'src/api/chat.js',
      why: '这里不用普通 axios，而是用 fetch 读取 SSE 流式返回。',
      x: 610,
      y: 210,
    },
    {
      id: 'chatRequest',
      kind: 'variable',
      name: 'ChatRequest.conversation_id',
      value: 'conversation_id: currentId || null',
      file: 'backend/main.py',
      why: '后端用这个字段判断是新对话还是接着旧对话继续问。',
      x: 930,
      y: 90,
    },
    {
      id: 'knowledgeBaseId',
      kind: 'variable',
      name: 'knowledge_base_id',
      value: 'knowledge_base_id: selectedKnowledgeBaseId',
      file: 'backend/main.py',
      why: '后端拿它来锁定本次检索的知识库范围。',
      x: 930,
      y: 250,
    },
    {
      id: 'effectiveQuestion',
      kind: 'method',
      name: '_build_effective_question()',
      value: 'question + 图片描述',
      file: 'backend/main.py',
      why: '如果用户发了图片，这一步会把图片描述合并进真正用于检索的问题。',
      x: 930,
      y: 410,
    },
    {
      id: 'retrievalQuestion',
      kind: 'variable',
      name: 'retrieval_question',
      value: exampleQuestion,
      file: 'backend/main.py',
      why: '这是最终送去检索引擎的查询文本，可能已经做过记忆拼接或图像补充。',
      x: 1230,
      y: 410,
    },
    {
      id: 'retrieveKnowledge',
      kind: 'method',
      name: 'retrieve_knowledge()',
      value: 'return final_chunks, trace',
      file: 'backend/retrieval.py',
      why: 'RAG 检索总入口，负责多路召回、融合、重排，再产出最终上下文。',
      x: 1540,
      y: 410,
    },
    {
      id: 'queryPlan',
      kind: 'method',
      name: 'build_query_plan()',
      value: 'hyde_document / rewrites / keywords',
      file: 'backend/retrieval.py',
      why: '先让模型把问题拆成多个检索角度，再准备关键词兜底。',
      x: 1840,
      y: 90,
    },
    {
      id: 'keywordRecall',
      kind: 'method',
      name: 'keyword_recall()',
      value: '关键词命中的 chunk',
      file: 'backend/retrieval.py',
      why: '中文制度类问题里，关键词往往比纯向量更稳，能把“迟到 / 早退 / 30分钟 / 罚款”找回来。',
      x: 1840,
      y: 250,
    },
    {
      id: 'rrfFuse',
      kind: 'method',
      name: 'rrf_fuse()',
      value: '多路结果融合排序',
      file: 'backend/retrieval.py',
      why: '把原问题、HyDE、改写、关键词等多条路线的结果合成一份候选列表。',
      x: 2130,
      y: 170,
    },
    {
      id: 'rerankChunks',
      kind: 'method',
      name: 'rerank_chunks()',
      value: 'reranked chunks / failed trace',
      file: 'backend/retrieval.py',
      why: '再用 DeepSeek 给候选 chunk 排序；失败时也会保留前面的检索结果继续回答。',
      x: 2430,
      y: 170,
    },
    {
      id: 'context',
      kind: 'variable',
      name: 'context',
      value: '[来源: 公司规章制度.pdf]\\n第十一章 ...',
      file: 'backend/main.py',
      why: '这是最终喂给大模型看的知识库上下文，答案必须优先依据这里。',
      x: 2730,
      y: 90,
    },
    {
      id: 'sources',
      kind: 'variable',
      name: 'sources',
      value: '[{ file_name, content, rerank_score, rrf_score }]',
      file: 'backend/main.py',
      why: '前端“参考资料”面板看到的就是它，便于用户核对答案来源。',
      x: 2730,
      y: 250,
    },
    {
      id: 'streamDeepSeek',
      kind: 'method',
      name: '_stream_deepseek_response()',
      value: 'async generator: content chunks',
      file: 'backend/main.py',
      why: '模型回答不是一次性返回，而是按 SSE 一段段发给前端。',
      x: 3030,
      y: 170,
    },
    {
      id: 'traceRecorder',
      kind: 'method',
      name: 'TraceRecorder.add()',
      value: 'stage / function / creates / uses / params / result',
      file: 'backend/learning_trace.py',
      why: '每一步变量怎么变的，都会被记录成 trace，学习中心的回放就读这份数据。',
      x: 3030,
      y: 330,
    },
    {
      id: 'streamContent',
      kind: 'variable',
      name: 'streamContent',
      value: '30分钟以内为迟到或早退，一次罚款50元...',
      file: 'src/stores/chat.js',
      why: '前端收到每个 SSE 内容片段后，会不断把它拼进这个变量里。',
      x: 3340,
      y: 170,
    },
    {
      id: 'assistantMessage',
      kind: 'variable',
      name: 'assistant_message',
      value: 'Message(role="assistant", content=full, ragas_status="pending")',
      file: 'backend/main.py / backend/models.py',
      why: '只有模型完整回答成功后，才会把 assistant 消息正式落库。',
      x: 3340,
      y: 40,
    },
    {
      id: 'ragasStatus',
      kind: 'variable',
      name: 'ragas_status',
      value: 'pending -> running -> done / failed',
      file: 'backend/models.py / backend/ragas_eval.py',
      why: 'RAGAS 是异步评估，不应该挡住用户先看到答案。',
      x: 3340,
      y: 330,
    },
    {
      id: 'scheduleRagas',
      kind: 'method',
      name: 'schedule_ragas_evaluation()',
      value: 'asyncio.create_task(...)',
      file: 'backend/ragas_eval.py',
      why: '回答保存成功后，后台再悄悄触发质量评估。',
      x: 3340,
      y: 490,
    },
  ],
  edges: [
    ['question', 'sendMessage', '函数参数'],
    ['attachments', 'sendMessage', '函数参数'],
    ['selectedKnowledgeBaseId', 'sendMessage', 'Pinia 状态'],
    ['sendMessage', 'streamChat', 'API 封装'],
    ['streamChat', 'chatRequest', 'JSON body'],
    ['streamChat', 'knowledgeBaseId', 'JSON body'],
    ['chatRequest', 'effectiveQuestion', 'Pydantic 字段'],
    ['knowledgeBaseId', 'effectiveQuestion', '知识库绑定'],
    ['effectiveQuestion', 'retrievalQuestion', 'return value'],
    ['retrievalQuestion', 'retrieveKnowledge', '函数参数'],
    ['retrieveKnowledge', 'queryPlan', '内部调用'],
    ['queryPlan', 'keywordRecall', 'keywords'],
    ['queryPlan', 'rrfFuse', 'vector routes'],
    ['keywordRecall', 'rrfFuse', 'keyword route'],
    ['rrfFuse', 'rerankChunks', '候选 chunks'],
    ['rerankChunks', 'context', 'final chunks'],
    ['rerankChunks', 'sources', '_build_sources()'],
    ['context', 'streamDeepSeek', 'prompt context'],
    ['sources', 'streamContent', 'SSE sources'],
    ['streamDeepSeek', 'streamContent', 'SSE content'],
    ['streamDeepSeek', 'assistantMessage', 'full answer'],
    ['traceRecorder', 'streamContent', 'SSE trace'],
    ['assistantMessage', 'ragasStatus', '字段写入'],
    ['assistantMessage', 'scheduleRagas', 'message_id'],
    ['scheduleRagas', 'ragasStatus', '后台更新'],
  ],
}

export const demoPath = [
  'question',
  'attachments',
  'selectedKnowledgeBaseId',
  'sendMessage',
  'streamChat',
  'chatRequest',
  'knowledgeBaseId',
  'effectiveQuestion',
  'retrievalQuestion',
  'retrieveKnowledge',
  'queryPlan',
  'keywordRecall',
  'rrfFuse',
  'rerankChunks',
  'context',
  'sources',
  'streamDeepSeek',
  'traceRecorder',
  'streamContent',
  'assistantMessage',
  'ragasStatus',
  'scheduleRagas',
]

export const branchSpecs = [
  {
    title: 'DeepSeek 规划失败',
    symbol: 'build_query_plan()',
    file: 'backend/retrieval.py',
    text: '规划失败时会回退到关键词兜底，不会让整条链路直接中断。',
  },
  {
    title: 'rerank 失败',
    symbol: 'rerank_chunks()',
    file: 'backend/retrieval.py',
    text: 'DeepSeek 重排失败后，系统仍然保留前面的召回结果继续回答。',
  },
  {
    title: 'assistant_save_failed',
    symbol: 'assistant_save_failed',
    file: 'backend/main.py',
    text: '答案已经生成，但落库失败时会记录 trace，不会把假成功展示给用户。',
  },
  {
    title: 'RAGAS failed',
    symbol: 'ragas_failed',
    file: 'backend/ragas_eval.py',
    text: '评估失败只会更新 ragas_status，不会影响已经返回的回答。',
  },
  {
    title: 'attachments / image_analysis',
    symbol: '_build_effective_question()',
    file: 'backend/main.py',
    text: '图片附件会先走视觉分析，再合并到 effective_question 里一起检索。',
  },
]

export const symbolToNodeId = {
  question: 'question',
  attachments: 'attachments',
  selectedKnowledgeBaseId: 'selectedKnowledgeBaseId',
  stream_chat: 'streamChat',
  'chatStore.sendMessage()': 'sendMessage',
  sendMessage: 'sendMessage',
  streamChat: 'streamChat',
  'ChatRequest.conversation_id': 'chatRequest',
  knowledge_base_id: 'knowledgeBaseId',
  _build_effective_question: 'effectiveQuestion',
  '_build_effective_question()': 'effectiveQuestion',
  retrieval_question: 'retrievalQuestion',
  retrieve_knowledge: 'retrieveKnowledge',
  'retrieve_knowledge()': 'retrieveKnowledge',
  build_query_plan: 'queryPlan',
  'build_query_plan()': 'queryPlan',
  keyword_recall: 'keywordRecall',
  'keyword_recall()': 'keywordRecall',
  rrf_fuse: 'rrfFuse',
  'rrf_fuse()': 'rrfFuse',
  rerank_chunks: 'rerankChunks',
  'rerank_chunks()': 'rerankChunks',
  context: 'context',
  sources: 'sources',
  _stream_deepseek_response: 'streamDeepSeek',
  '_stream_deepseek_response()': 'streamDeepSeek',
  'TraceRecorder.add()': 'traceRecorder',
  streamContent: 'streamContent',
  assistant_message: 'assistantMessage',
  ragas_status: 'ragasStatus',
  schedule_ragas_evaluation: 'scheduleRagas',
  'schedule_ragas_evaluation()': 'scheduleRagas',
  request_received: 'streamChat',
  request_rejected: 'streamChat',
  input_normalized: 'effectiveQuestion',
  retrieval_completed: 'retrieveKnowledge',
  context_built: 'context',
  first_content_chunk: 'streamContent',
  assistant_ready_to_save: 'assistantMessage',
  assistant_message_saved: 'assistantMessage',
  assistant_save_failed: 'assistantMessage',
  ragas_scheduled: 'scheduleRagas',
  ragas_schedule_failed: 'scheduleRagas',
  memory_summary_check_scheduled: 'scheduleRagas',
}

export function getNodeById(nodeId) {
  return flowSpec.nodes.find((node) => node.id === nodeId) || null
}

export function getNodeIdBySymbol(symbol) {
  return symbolToNodeId[symbol] || ''
}
