export const exampleQuestion = '员工迟到、早退在 30 分钟以内，公司会如何处罚？'

export const flowSpec = {
  width: 4620,
  height: 980,
  nodes: [
    {
      id: 'question',
      kind: 'variable',
      name: 'question',
      value: exampleQuestion,
      file: 'src/views/Chat.vue',
      why: '用户在智能问答页输入的原始问题，是整条链路的起点。',
      x: 40,
      y: 90,
    },
    {
      id: 'attachments',
      kind: 'variable',
      name: 'attachments',
      value: '[]',
      file: 'src/views/Chat.vue',
      why: '聊天页允许同时携带图片附件；图片会先被转成文本描述，再进入同一条问答链路。',
      x: 40,
      y: 250,
    },
    {
      id: 'selectedKnowledgeBaseId',
      kind: 'variable',
      name: 'selectedKnowledgeBaseId',
      value: '7',
      file: 'src/views/Chat.vue / src/stores/chat.js',
      why: '前端选中的知识库 id 会随请求发送，后端据此做 SQL 与 Chroma 的知识库隔离。',
      x: 40,
      y: 410,
    },
    {
      id: 'sendMessage',
      kind: 'method',
      name: 'chatStore.sendMessage()',
      value: 'sendMessage(question, attachments)',
      file: 'src/stores/chat.js',
      why: 'Pinia 方法把页面输入整理成流式聊天请求，并负责拼接 SSE 内容。',
      x: 310,
      y: 210,
    },
    {
      id: 'streamChat',
      kind: 'method',
      name: 'streamChat()',
      value: 'fetch(`${API_BASE_URL}/chat/stream`, ...)',
      file: 'src/api/chat.js',
      why: '前端用 fetch 读取后端 SSE 流，持续接收 trace、sources 和 content chunk。',
      x: 610,
      y: 210,
    },
    {
      id: 'chatRequest',
      kind: 'variable',
      name: 'ChatRequest',
      value: 'conversation_id / knowledge_base_id / question / attachments',
      file: 'backend/schema/schemas.py',
      why: 'FastAPI 使用这个请求模型承接前端输入，决定新建会话还是续写旧会话。',
      x: 930,
      y: 40,
    },
    {
      id: 'knowledgeBaseId',
      kind: 'variable',
      name: 'knowledge_base_id',
      value: 'knowledge_base_id: selectedKnowledgeBaseId',
      file: 'backend/service/chat_service.py',
      why: '后端会解析并锁定本轮使用的知识库，避免不同知识库内容串库。',
      x: 930,
      y: 180,
    },
    {
      id: 'effectiveQuestion',
      kind: 'method',
      name: '_build_effective_question()',
      value: 'question + image description',
      file: 'backend/rag/vision_service.py',
      why: '如果请求带图片，系统先做图片分析，再把描述合并到真正用于检索和生成的问题里。',
      x: 930,
      y: 320,
    },
    {
      id: 'conversationState',
      kind: 'variable',
      name: 'conversation',
      value: 'conversation_created / conversation_loaded',
      file: 'backend/service/chat_service.py',
      why: '后端在这里确定会话状态，新会话会创建标题，旧会话会复用原绑定知识库。',
      x: 1230,
      y: 120,
    },
    {
      id: 'userMessage',
      kind: 'variable',
      name: 'user_message',
      value: 'Message(role="user", content=display_question)',
      file: 'backend/service/chat_service.py / backend/model/models.py',
      why: '用户消息先落库，随后记忆窗口会排除这条当前消息，避免重复塞进 prompt。',
      x: 1230,
      y: 300,
    },
    {
      id: 'memoryContext',
      kind: 'variable',
      name: 'memory_context',
      value: 'long summary + recent window',
      file: 'backend/rag/memory_service.py',
      why: '记忆上下文由长期摘要和最近对话窗口拼接；滑出窗口的完整轮次进入长期记忆，短期超长时才压缩近期窗口。',
      x: 1230,
      y: 480,
    },
    {
      id: 'retrievalQuestion',
      kind: 'variable',
      name: 'retrieval_question',
      value: exampleQuestion,
      file: 'backend/rag/memory_service.py',
      why: '这是送入 RAG 检索的最终查询文本，可能已经包含记忆消解和图片描述。',
      x: 1540,
      y: 300,
    },
    {
      id: 'ragGate',
      kind: 'method',
      name: 'decide_need_rag()',
      value: 'need_rag: true / false',
      file: 'backend/tool/tools.py',
      why: 'LangChain tool 先判断本轮是否需要知识库；直答问题会跳过 RAG 和 RAGAS。',
      x: 1540,
      y: 480,
    },
    {
      id: 'langchainAgent',
      kind: 'method',
      name: 'create_agent()',
      value: 'LangChain Agent -> tools -> reflection',
      file: 'backend/agent/agent.py',
      why: 'LangChain Agent 负责受控规划检索查询，再调用检索工具；项目仍限制最多 2 轮。',
      x: 1840,
      y: 320,
    },
    {
      id: 'retrieveKnowledge',
      kind: 'method',
      name: 'retrieve_knowledge()',
      value: 'return final_chunks, trace',
      file: 'backend/tool/tools.py',
      why: '这是 Agent 调用的真实检索工具，内部完成多路召回、RRF 融合、rerank 和 trace 输出。',
      x: 1840,
      y: 500,
    },
    {
      id: 'queryPlan',
      kind: 'method',
      name: 'build_query_plan()',
      value: 'hyde_document / rewrites / keywords',
      file: 'backend/tool/tools.py',
      why: 'LangChain tool 调用模型生成 HyDE、改写和关键词，为多路检索准备查询。',
      x: 2140,
      y: 90,
    },
    {
      id: 'keywordRecall',
      kind: 'method',
      name: 'keyword_recall()',
      value: 'keyword matched chunks',
      file: 'backend/tool/tools.py',
      why: '关键词召回从 MySQL 原文中补充制度类命中，弥补纯向量检索的不稳定。',
      x: 2140,
      y: 250,
    },
    {
      id: 'rrfFuse',
      kind: 'method',
      name: 'rrf_fuse()',
      value: 'fused candidates',
      file: 'backend/tool/tools.py',
      why: 'RRF 把原问题、HyDE、改写、关键词等多路候选合并成一组排序结果。',
      x: 2730,
      y: 170,
    },
    {
      id: 'rerankChunks',
      kind: 'method',
      name: 'rerank_chunks()',
      value: 'reranked chunks / failed trace',
      file: 'backend/tool/tools.py',
      why: '最后用模型给候选 chunk 相关性打分；失败时保留融合结果继续回答。',
      x: 2430,
      y: 170,
    },
    {
      id: 'context',
      kind: 'variable',
      name: 'context',
      value: '[来源: 公司规章制度.pdf]\\n第十一章...',
      file: 'backend/service/chat_service.py',
      why: '最终选中的 chunk 会拼成知识库上下文，进入 LangChain 生成链。',
      x: 3030,
      y: 90,
    },
    {
      id: 'sources',
      kind: 'variable',
      name: 'sources',
      value: '[{ file_name, content, rerank_score, rrf_score }]',
      file: 'backend/service/utils_service.py',
      why: '前端参考资料抽屉展示的来源数据来自这里。',
      x: 3030,
      y: 250,
    },
    {
      id: 'langchainGeneration',
      kind: 'method',
      name: 'stream_rag_answer()',
      value: 'ChatOpenAI.astream()',
      file: 'backend/rag/chains.py',
      why: '最终回答由 LangChain ChatOpenAI 流式生成，失败时按现有规则切到文本后备模型。',
      x: 3330,
      y: 170,
    },
    {
      id: 'traceRecorder',
      kind: 'method',
      name: 'TraceRecorder.add()',
      value: 'stage / function / creates / uses / params / result',
      file: 'backend/rag/learning_trace.py',
      why: '主链路持续写入 trace，学习中心真实回放读取这些事件来高亮节点。',
      x: 3330,
      y: 330,
    },
    {
      id: 'streamContent',
      kind: 'variable',
      name: 'streamContent',
      value: '30 分钟以内为迟到或早退...',
      file: 'src/stores/chat.js',
      why: '前端收到每个 SSE content 片段后持续拼接成正在生成的回答。',
      x: 3640,
      y: 170,
    },
    {
      id: 'assistantMessage',
      kind: 'variable',
      name: 'assistant_message',
      value: 'Message(role="assistant", content=full, ragas_status="pending")',
      file: 'backend/service/chat_service.py / backend/model/models.py',
      why: '只有模型完整回答成功后，assistant 消息才会正式落库。',
      x: 3940,
      y: 40,
    },
    {
      id: 'memoryCompaction',
      kind: 'method',
      name: '_schedule_memory_summary_update()',
      value: 'slipped turns -> memory_summary',
      file: 'backend/rag/memory_service.py',
      why: '回答保存后检查最近窗口是否滑动；滑出的完整问答轮次会合并进长期记忆，长期记忆超长时再二次摘要。',
      x: 3940,
      y: 220,
    },
    {
      id: 'ragasStatus',
      kind: 'variable',
      name: 'ragas_status',
      value: 'pending -> running -> done / failed',
      file: 'backend/model/models.py / backend/rag/ragas_eval.py',
      why: 'RAGAS 是异步评估，不阻塞用户先看到答案。',
      x: 4240,
      y: 130,
    },
    {
      id: 'scheduleRagas',
      kind: 'method',
      name: 'schedule_ragas_evaluation()',
      value: 'async RAGAS evaluation',
      file: 'backend/rag/ragas_eval.py',
      why: 'RAG 回答保存成功后才启动 RAGAS；直答问题不会启动 RAGAS。',
      x: 4240,
      y: 310,
    },
  ],
  edges: [
    ['question', 'sendMessage', 'user input'],
    ['attachments', 'sendMessage', 'optional'],
    ['selectedKnowledgeBaseId', 'sendMessage', 'Pinia state'],
    ['sendMessage', 'streamChat', 'API call'],
    ['streamChat', 'chatRequest', 'JSON body'],
    ['streamChat', 'knowledgeBaseId', 'JSON body'],
    ['chatRequest', 'effectiveQuestion', 'validated input'],
    ['knowledgeBaseId', 'effectiveQuestion', 'scope'],
    ['effectiveQuestion', 'conversationState', 'create/load'],
    ['knowledgeBaseId', 'conversationState', 'bind KB'],
    ['conversationState', 'userMessage', 'save user'],
    ['userMessage', 'memoryContext', 'previous messages'],
    ['memoryContext', 'retrievalQuestion', 'disambiguate'],
    ['retrievalQuestion', 'ragGate', 'route input'],
    ['effectiveQuestion', 'ragGate', 'route input'],
    ['memoryContext', 'ragGate', 'route input'],
    ['ragGate', 'langchainAgent', 'need_rag = true'],
    ['retrievalQuestion', 'langchainAgent', 'agent input'],
    ['langchainAgent', 'retrieveKnowledge', 'tool call'],
    ['retrieveKnowledge', 'queryPlan', 'planning'],
    ['queryPlan', 'keywordRecall', 'keywords'],
    ['queryPlan', 'rrfFuse', 'vector routes'],
    ['keywordRecall', 'rrfFuse', 'keyword route'],
    ['rrfFuse', 'rerankChunks', 'candidate chunks'],
    ['rerankChunks', 'context', 'final chunks'],
    ['rerankChunks', 'sources', '_build_sources()'],
    ['context', 'langchainGeneration', 'prompt context'],
    ['sources', 'streamContent', 'SSE sources'],
    ['langchainGeneration', 'streamContent', 'SSE content'],
    ['langchainGeneration', 'assistantMessage', 'full answer'],
    ['traceRecorder', 'streamContent', 'SSE trace'],
    ['assistantMessage', 'scheduleRagas', 'message_id'],
    ['assistantMessage', 'memoryCompaction', 'conversation_id'],
    ['scheduleRagas', 'ragasStatus', 'async update'],
    ['memoryCompaction', 'ragasStatus', 'parallel background'],
  ],
}

export const demoPath = [
  'question',
  'attachments',
  'selectedKnowledgeBaseId',
  'sendMessage',
  'streamChat',
  'chatRequest',
  'knowledgeBaseId',
  'effectiveQuestion',
  'conversationState',
  'userMessage',
  'memoryContext',
  'retrievalQuestion',
  'ragGate',
  'langchainAgent',
  'retrieveKnowledge',
  'queryPlan',
  'keywordRecall',
  'rrfFuse',
  'rerankChunks',
  'context',
  'sources',
  'langchainGeneration',
  'traceRecorder',
  'streamContent',
  'assistantMessage',
  'scheduleRagas',
  'memoryCompaction',
  'ragasStatus',
]

export const branchSpecs = [
  {
    title: 'LangChain Agent plan failed',
    symbol: 'langchain_agent_plan_failed',
    file: 'backend/agent/agent.py',
    text: 'Agent 规划失败时回退到原始问题检索，不中断主聊天链路。',
  },
  {
    title: 'retrieve_knowledge failed',
    symbol: 'langchain_tool_failed',
    file: 'backend/tool/tools.py',
    text: '检索工具异常会写入 trace，并返回空上下文让流式回答安全结束。',
  },
  {
    title: 'rerank failed',
    symbol: 'rerank_chunks()',
    file: 'backend/tool/tools.py',
    text: '重排失败后，系统仍保留 RRF 融合结果继续回答。',
  },
  {
    title: 'generation fallback',
    symbol: 'langchain_text_fallback_started',
    file: 'backend/rag/llm.py',
    text: 'DeepSeek 流式生成失败时，LangChain 链会尝试文本后备模型。',
  },
  {
    title: 'attachments / image_analysis',
    symbol: '_build_effective_question()',
    file: 'backend/rag/vision_service.py',
    text: '图片附件先走视觉分析，再合并到 effective_question 进入同一条链路。',
  },
]

export const symbolToNodeId = {
  question: 'question',
  attachments: 'attachments',
  selectedKnowledgeBaseId: 'selectedKnowledgeBaseId',
  stream_chat: 'streamChat',
  'chatStore.sendMessage()': 'sendMessage',
  sendMessage: 'sendMessage',
  streamChat: 'streamChat',
  ChatRequest: 'chatRequest',
  'ChatRequest.conversation_id': 'chatRequest',
  knowledge_base_id: 'knowledgeBaseId',
  memory_context: 'memoryContext',
  _build_memory_context: 'memoryContext',
  '_build_memory_context()': 'memoryContext',
  _build_memory_aware_retrieval_question: 'retrievalQuestion',
  '_build_memory_aware_retrieval_question()': 'retrievalQuestion',
  decide_need_rag: 'ragGate',
  'decide_need_rag()': 'ragGate',
  rag_gate_decided: 'ragGate',
  retrieval_skipped: 'langchainGeneration',
  conversation_created: 'conversationState',
  conversation_loaded: 'conversationState',
  user_message_saved: 'userMessage',
  memory_built: 'memoryContext',
  effective_question_built: 'effectiveQuestion',
  generation_started: 'langchainGeneration',
  _build_effective_question: 'effectiveQuestion',
  '_build_effective_question()': 'effectiveQuestion',
  agentic_retrieve_knowledge: 'langchainAgent',
  'agentic_retrieve_knowledge()': 'langchainAgent',
  create_agent: 'langchainAgent',
  'create_agent()': 'langchainAgent',
  langchain_agent_started: 'langchainAgent',
  langchain_agent_planned: 'langchainAgent',
  langchain_agent_plan_failed: 'langchainAgent',
  langchain_agent_reflected: 'langchainAgent',
  langchain_agent_finished: 'langchainAgent',
  retrieval_question: 'retrievalQuestion',
  retrieve_knowledge: 'retrieveKnowledge',
  'retrieve_knowledge()': 'retrieveKnowledge',
  retrieval_completed: 'retrieveKnowledge',
  langchain_tool_called: 'retrieveKnowledge',
  langchain_tool_failed: 'retrieveKnowledge',
  langchain_retriever_done: 'retrieveKnowledge',
  context_built: 'context',
  build_query_plan: 'queryPlan',
  'build_query_plan()': 'queryPlan',
  keyword_recall: 'keywordRecall',
  'keyword_recall()': 'keywordRecall',
  rrf_fuse: 'rrfFuse',
  'rrf_fuse()': 'rrfFuse',
  rerank_chunks: 'rerankChunks',
  'rerank_chunks()': 'rerankChunks',
  context: 'context',
  sources: 'sources',
  stream_rag_answer: 'langchainGeneration',
  'stream_rag_answer()': 'langchainGeneration',
  _stream_deepseek_response: 'langchainGeneration',
  '_stream_deepseek_response()': 'langchainGeneration',
  langchain_generation_prompt_built: 'langchainGeneration',
  langchain_generation_failed: 'langchainGeneration',
  langchain_text_fallback_started: 'langchainGeneration',
  langchain_text_fallback_failed: 'langchainGeneration',
  'TraceRecorder.add()': 'traceRecorder',
  streamContent: 'streamContent',
  first_content_chunk: 'streamContent',
  assistant_message: 'assistantMessage',
  assistant_ready_to_save: 'assistantMessage',
  assistant_message_saved: 'assistantMessage',
  assistant_save_failed: 'assistantMessage',
  assistant_not_saved: 'assistantMessage',
  ragas_status: 'ragasStatus',
  schedule_ragas_evaluation: 'scheduleRagas',
  'schedule_ragas_evaluation()': 'scheduleRagas',
  ragas_scheduled: 'scheduleRagas',
  ragas_schedule_failed: 'scheduleRagas',
  ragas_skipped: 'scheduleRagas',
  _schedule_memory_summary_update: 'memoryCompaction',
  '_schedule_memory_summary_update()': 'memoryCompaction',
  _maybe_compact_memory_summary: 'memoryCompaction',
  '_maybe_compact_memory_summary()': 'memoryCompaction',
  memory_summary_update_scheduled: 'memoryCompaction',
  memory_summary_update_schedule_failed: 'memoryCompaction',
  memory_summary_update_skipped: 'memoryCompaction',
  memory_summary_update_triggered: 'memoryCompaction',
  memory_summary_update_fallback: 'memoryCompaction',
  memory_summary_updated: 'memoryCompaction',
  memory_summary_update_failed: 'memoryCompaction',
  recent_memory_compaction_triggered: 'memoryCompaction',
  recent_memory_compacted: 'memoryCompaction',
  recent_memory_compaction_fallback: 'memoryCompaction',
  memory_summary_compaction_skipped: 'memoryCompaction',
  memory_summary_compaction_triggered: 'memoryCompaction',
  memory_summary_compaction_failed: 'memoryCompaction',
  memory_summary_compacted: 'memoryCompaction',
  generation_failed: 'langchainGeneration',
  image_failed_directly: 'effectiveQuestion',
  request_received: 'streamChat',
  request_rejected: 'streamChat',
  input_normalized: 'effectiveQuestion',
}

export function getNodeById(nodeId) {
  return flowSpec.nodes.find((node) => node.id === nodeId) || null
}

export function getNodeIdBySymbol(symbol) {
  return symbolToNodeId[symbol] || ''
}
